// constants/quests.ts
import { Quest } from "../types";

export const ALL_AVAILABLE_QUESTS: Quest[] = [
  {
    id: "1",
    title: "聖なる水を飲む",
    description: "コップ一杯の水を飲んで身体を目覚めさせる",
    icon: "water",
    expReward: 10,
    goldReward: 5,
  },
  {
    id: "2",
    title: "太陽の光を浴びる",
    description: "5分間、外の空気を吸ってリフレッシュする",
    icon: "white-balance-sunny",
    expReward: 20,
    goldReward: 10,
  },
  {
    id: "3",
    title: "身体の解放",
    description: "簡単なストレッチで血行を促進する",
    icon: "run",
    expReward: 15,
    goldReward: 7,
  },
  {
    id: "4",
    title: "深呼吸の儀式",
    description: "3回ゆっくりと深呼吸して脳に酸素を送る",
    icon: "weather-windy",
    expReward: 10,
    goldReward: 4,
  },
  {
    id: "5",
    title: "階段の試練",
    description: "1フロア分の階段を上り下りする",
    icon: "stairs",
    expReward: 25,
    goldReward: 12,
  },
  {
    id: "6",
    title: "ツボ押し",
    description: "手の甲にある眠気覚ましのツボを押す",
    icon: "hand-pointing-up",
    expReward: 10,
    goldReward: 5,
  },
  {
    id: "7",
    title: "ミントの刺激",
    description: "ガムを噛んだり歯を磨いて脳を活性化",
    icon: "leaf",
    expReward: 5,
    goldReward: 3,
  },
  {
    id: "8",
    title: "冷水の手洗い",
    description: "冷たい水で顔や手を洗ってリフレッシュ",
    icon: "hand-water",
    expReward: 15,
    goldReward: 6,
  },
  {
    id: "9",
    title: "音楽の力",
    description: "アップテンポな曲を1曲聴いて気分を上げる",
    icon: "music",
    expReward: 10,
    goldReward: 4,
  },
  {
    id: "10",
    title: "換気の魔法",
    description: "窓を開けて部屋の空気を入れ替える",
    icon: "window-open-variant",
    expReward: 15,
    goldReward: 8,
  },
  {
    id: "11",
    title: "場所移動",
    description: "数分間だけ別の場所に移動して作業する",
    icon: "swap-horizontal",
    expReward: 10,
    goldReward: 5,
  },
  {
    id: "12",
    title: "1分間ジャーナル",
    description: "今の気分やタスクを1分で書き出す",
    icon: "pencil",
    expReward: 20,
    goldReward: 10,
  },
  {
    id: "13",
    title: "タスクの分解",
    description: "大きなタスクを3つの小さなステップに分ける",
    icon: "playlist-edit",
    expReward: 25,
    goldReward: 15,
  },
];

export const QUESTS_TO_SHOW = 4; // 一度に表示するクエストの数
